version: '3.8'
services:
  mongodb:
    image: mongo:jammy
    container_name: chat_app
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
      MONGO_INITDB_DATABASE: chat_app
    ports:
      - '27018:27017'
    volumes:
      - chatapp-data:/data/db
      - ./docker/init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js:ro
    restart: always
  redis-chat:
    image: docker.io/redis:7.2.3
    container_name: redis-chat
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
volumes:
  chatapp-data:
  redis-data: