spring:
  data:
    mongodb:
      username: ${MONGO_DB_USERNAME}
      password: ${MONGO_DB_PASSWORD}
      #      host: ${MONGO_DB_HOST}
      #      port: ${MONGO_DB_PORT}
      database: ${MONGO_DB_DATABASE}
      uri: ${MONGO_DB_URI}

    redis:
      port: ${REDIS_PORT}
      host: ${REDIS_HOST}
  sql:
    init:
      encoding: UTF-8
  main:
    allow-bean-definition-overriding: true

outbound:
  identity:
    client-id: ${CLIENT_ID}
    client-secret: ${CLIENT_SECRET}
    redirect-uri: ${REDIRECT_URI}

jwt:
  signer-key: ${JWT_SIGNING_KEY}
  expiration-duration: ${JWT_EXPIRATION_DURATION} # in sec
  refreshable-duration: ${JWT_REFRESHABLE_DURATION} # in sec

server:
  port: 8080
  servlet:
    encoding:
      charset: utf-8
      force: true
      enabled: true

momo:
  secret-key: ${MOMO_SECRET_KEY}
  access-key: ${MOMO_ACCESS_KEY}
  #  order-type: ${MOMO_ORDER_TYPE}
  request-type: ${MOMO_REQUEST_TYPE}
  #  pay-type: ${MOMO_PAY_TYPE}
  redirect-url: ${MOMO_REDIRECT_URL}
  ipn-url: ${MOMO_IPN_URL}
  base-url: ${MOMO_BASE_URL}
  id-momo: ${MOMO_ID_MOMO}

application:
  api:
    prefix: /api
    url: ${API_URL}
  frontend:
    url: ${FRONT_END_PREFIX}